### ISSUE TITLE
Brainstorm: Why do we need another command line task manager

### ISSUE THREAD

**Issue by xerus2000** [lyz-code/pydo#73]
After hijacking #40 and #42, I'll open a separate issue here.

I feel like we have similar ideas, but we are not quite aligned on the vision. I am still wondering whether it makes sense to write yet another task manager from scratch. I think it is better to create a suite of tools instead of creating a new personalized, specific tool.
So, a program to add and keep track of tasks. Time-tracking is an own module. Parsing dates and intervals is an own module. Heck, even transforming the CLI input into machine-readable form could be an own module. That way each can be reused independently.
I think taskwarrior does many things right, but in the end it is again a big monolith, so the only way to solve fundamental issues is writing a new tool.

Have you considered creating a wrapper tool for tasklite or taskwarrior rather than writing a new one from scratch? Then you could still use your programming language of choice but don't have to rewrite all the parsing and backend stuff.

I am in the process of writing my own task manager specification at https://github.com/xerus2000/howtodo
Right now it is more of a braindump, but I plan on bringing a proper structure into it.

Let me know what you think :)

**Comment by lyz-code** [comment]
The question of whether it makes sense to create yet another command line task manager has been thoroughly documented in the docs and in the issues you mentioned. So I won't repeat myself here. If you feel that a specific point is not clear, we can clarify it, otherwise bear with me in not generally discussing it again.

This project is founded (not lightly) in the idea that we need a new task manager, so if you are not sure, that's fine. We are building it in a way that can easily be used as a python library, so if you like the modules we are building but not the tool, that's fine too! You can reuse them to built your suite of tools the way you see it. For us, it makes more sense to build a tool that aggregates all the functionality we want in a task manager.

After years of building wrappers over taskwarrior, we decided to use all that knowledge to create something from scratch that will natively accomplish the features we want and stop building patch solutions. If you want to follow that path, be warned that you don't end up with a low performance, unmaintained, out of date software.

It's awesome that you are writing your own specification :). The more brains spending cpu cycles in this topic the better. Each project (taskwarrior, tasklite, pydo, ...) is or has been through  that braindump process and has ended with a different solution. I encourage you to check the code of these projects to try to grasp the idea of why are they doing the things they do. So when you are done with it, you can make an informed decision whether you want to transform one of the existent projects or build your own solution if nothing fits your needs.

Good luck :)

**Comment by lyz-code** [comment]
Closing for unactivity, if you want to follow up the discussion I'll reopen it
